#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Start Container
# -------------------------------------------------------------------------------------------
PORT=9030
ORG=`../../getServiceName 1`
SERVICE=`../../getServiceName 4`
API=`../../getServiceName 3`
echo "docker container run --name $SERVICE -d --rm -p $PORT:9090 $ORG/$SERVICE"
echo "Checkout API: http://localhost:$PORT/api/v1/$API/swagger-ui.html"
docker container run --name $SERVICE -it --rm -p $PORT:9090 $ORG/$SERVICE
